- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: kezban
    ansible_ssh_private_key_file: "/home/ec2-user/my_key.pem"  #Makinanın içinde nerdeyse key_pem onun yolunu yapıştırmak gerekir
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"  #ansible-playbook user.yml -i inventory_aws_ec2.yml terminalde yaml çalıştırmak için.
                            #ansible all -a "tail -2 /etc/passwd" oluşan kullanıcılara görmek için