

- name: Apache installation for ubuntuservers
  hosts: ubuntuservers
  tasks:
   - name: update
     ansible.builtin.shell: "apt update -y"
     
   - name: install the latest version of Apache
     ansible.builtin.apt:
       name: apache2
       state: latest